sass:
  style: compact

exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - build.sh
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
